### ISSUE TITLE
The reported results of baselines ?

### ISSUE THREAD

**Issue by lshowway** [studio-ousia/luke#100]
The reported results of `ERNIE, KEPLER, KnowBERT, K-Adapter` are based on `ROBERTA-large` ?

**Comment by ikuyamada** [comment]
As we used the results reported in the original papers, please refer to the corresponding papers.

**Comment by lshowway** [comment]
@ikuyamada LUKE reports the results based on `ROBERTA-large`, while the mentioned baselines are not based on `ROBERTA-large`, e.g., KnowBert is based on  `bert-base-uncased`. Therefore, I have a question, are LUKE and mentioned baselines compared fairly?

**Comment by ikuyamada** [comment]
LUKE is based on RoBERTa-large because at the time of writing the paper, the state-of-the-art model of our entity-related tasks was the K-Adapter model which is based on RoBERTa-large. Although comparison with a model based on smaller PLM (e.g., KnowBERT) may not be a fair comparison, it is also difficult to run expensive pretraining multiple times due to our limited computational budget.
