### ISSUE TITLE
Issue to pretrain with multiple GPUs

### ISSUE THREAD

**Issue by jplu** [studio-ousia/luke#106]
Hi,

I'm currently trying to pretrain Luke on a specific language for some experiments. While the entire process (preparing the dataset and running the training) is going well, I tried to used the `--parallel` argument and the training time has been multiplied by ~4.

My setup / environment:
OS: Ubuntu
Python: conda with Python 3.7
install: used Poetry
Pytorch: 1.10.1+cu113
GPU: 4 x RTX 3090

Without the `--parallel` argument, for a single epoch, the announced training time is ~800 hours while with this argument the training time increases until ~4000 hours. Here the command line I'm using:

```
python -m luke.cli pretrain ./wikipedia_pretrain_dataset my-luke --bert-model-name camembert-large --entity-emb-size 300 --learning-rate 3e-5 --warmup 10000 --log-dir logs/
```

After checking the source code, I haven't seen any trace of `DistributedDataParallel` that is the recommended way to go when dealing with distributed/parallel training in PyTorch, as suggested in the [documentation](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html).

Any suggestion that might help to find where the bottleneck is?

Thanks a lot for your help!

**Comment by ikuyamada** [comment]
Hi @jplu,

Thank you for your interest in LUKE!

I think this may be due to the small training batch size per a GPU.
The batch size per a GPU is computed based on `batch_size / gradient_accumulation_steps / num_workers` (see [here](https://github.com/studio-ousia/luke/blob/master/luke/pretraining/train.py#L181)).
If you use the default hyper-parameters (`batch_size`: 2048, `gradient_accumulation_steps`: 1024) on 4 GPUs (`num_workers`: 4), the train batch size becomes less than one.

Also, the current code does not use `DistributedDataParallel`, and the parallel training is automatically executed when specifying `--parallel`.

**Comment by jplu** [comment]
Thanks for this clear answer! I have indeed overlooked that part as I'm used to have different computation formula for the total training batch size. My bad!

After changing this, it is now around twice faster indeed. Thanks a lot!!!
