### ISSUE TITLE
Convert examples to features

### ISSUE THREAD

**Issue by binhna** [studio-ousia/luke#116]
Hi, thanks for your great work.
I am not sure if I understand it correctly of this function: You iterate over all possible mentions (word boundary) and add it to `InputFeatures`, the `labels` index of each mention will be 0 if it is not an entity else it will be the index of the entity in the current sentence (entity index begins at 0)  `labels.append(entity_labels.get((doc_entity_start, doc_entity_end), 0))` . But the problem is the entity indices in the sentence begin with 0, so if you add 0 to the labels when mention is not an entity, this will lead to ambiguity between the first entity (index 0) and the non-entity mentioned. So is this a bug?

**Comment by ikuyamada** [comment]
Hi @binhna,
`labels` contains label indices rather than the position of the entity in the sentence. `entity_labels` is created based on `label_map` which is constructed by enumerating all labels (e.g., PERSON, LOCATION) in the dataset (see [here](https://github.com/studio-ousia/luke/blob/799b4d27d0421664e48268ad042c0e3638fad11b/examples/ner/utils.py#L98)).

**Comment by binhna** [comment]
Oh, I see. So in that case, the zero index in the `label_map` must be the `O` tag

**Comment by ikuyamada** [comment]
Yes, the index of the `NIL` label (corresponding to `O` tag) is zero (see [here](https://github.com/studio-ousia/luke/blob/master/examples/ner/utils.py#L57)).

**Comment by binhna** [comment]
Thanks, @ikuyamada
