### ISSUE TITLE
Entity self-awareness attention 

### ISSUE THREAD

**Issue by LihYanW** [studio-ousia/luke#132]
Hi @ikuyamada, I am currently trying out mLUKE for NER task. From the NER example, it seems like entity self-awareness as introduced in the LUKE paper was not implemented for mLUKE. May I understand why this feature is not implemented/recommended for mLUKE model, as the mLUKE paper did not elaborate on this as well. I tried running mLUKE with entity self awareness set to `True` and got poorer performance than without enabling it, and would like to understand better why this is so. 

Looking forward to your advice/inputs on this.

**Comment by Ryou0634** [comment]
Hi, thank you for your inquiry.
This is a good question and let me answer this.


#### Why is entity-aware attention not used in the mLUKE paper?

This is simply because we initially wanted to make the experiments simple and make the model comparison more reasonable.
In our mLUKE paper, we compare models with and without entity representations.
We want to make their settings as fair as possible, so did not use entity-aware attention (i.e., introducing additional parameters and mechanism).


#### Preliminary results of mLUKE with entity-aware attention
But we actually did try using entity-aware attention in mLUKE in cross-lingual transfer.
We did not perform rigid experiments, but it seems the results are mixed.
For example, in the task of relation extraction, we observed worse performance with entity-aware attention, but in QA, we observed slightly better performance.

We think this way. As entity-aware attention introduces additional parameters, the model is more likely to overfit to training data with entity-aware attention. In cross-lingual transfer settings, overfit may be more likely to happen as the training and test languages are different. So, with small datasets, entity-aware attention in mLUKE may not be effective.

**Comment by LihYanW** [comment]
@Ryou0634 Thank you so much, and appreciate your detailed response to this question.
