### ISSUE TITLE
Question about input feature entity type.

### ISSUE THREAD

**Issue by JHR0717** [studio-ousia/luke#23]
hello!
I am a new researcher about ner!
I have read your paper and the code, and I have a quesition about the entity type feature.
In your work, the input entity type feature coming from the labeled data.
But when we do the predict, we can't get the entity type from the unlabeled data, so how we create the input feature?

**Comment by ikuyamada** [comment]
Hi,
Maybe the name *entity type representation* is a bit confusing though, this representation denotes that the corresponding input token is an entity (not a word).
Therefore, the labeled data is not required to compute this representation.

**Comment by JHR0717** [comment]
Emmmm，I  still don't understand how to get the entity embedding……
How can we know which input token is an entity?

**Comment by ikuyamada** [comment]
In our EMNLP paper, we address the NER task by treating all possible spans (n-grams) as potential entity names and classify them  into the target entity types (e.g., PERSON, LOCATION) or non-entity type (i.e., the span is not an entity). Since we simultaneously address the detection and classification tasks, we do not need to know whether an input token is an entity.

**Comment by JHR0717** [comment]
Hummm，thank you for your answer!
