### ISSUE TITLE
Entity type embedding

### ISSUE THREAD

**Issue by yahshibu** [studio-ousia/luke#35]
Thank you for your impressive work!

I have a question about "entity type embedding", _**e**_. I'm wondering why entity type embedding is necessary. Your LUKE has two position embeddings for word and entity, _**C**<sub>i</sub>_ and _**D**<sub>i</sub>_, respectively.

To my understanding, _**D**<sub>i</sub>_ can contain information of _**e**_. We can create the logically same model by changing parameter values as follows: _**D**<sub>i</sub>_ <- _**D**<sub>i</sub>_ + _**e**_, _**e**_ <- _**0**_. In other words, _**D**<sub>i</sub>_ and _**e**_ seem to be redundant.

Why is entity type embedding necessary for LUKE? Does it help to make training more stable?

**Comment by ikuyamada** [comment]
Thank you for carefully reading our paper!

As you pointed out, entity type embedding may not be necessary, and it can be stored in the entity position embedding.
However, as the computational overhead of adding entity type embedding is negligible, our model stores the *token type* information in the dedicated entity type embedding vector instead of separate position embedding vectors.

**Comment by yahshibu** [comment]
I see. And, I agree that the computational overhead of adding entity type embedding is negligible.

Thank you for your quick and kind response!
