### ISSUE TITLE
Extract contextualized word representations for Bi-LSTM-CRF NER models?

### ISSUE THREAD

**Issue by steambread666** [studio-ousia/luke#64]
Hi, thanks for your code and instructions! I want to try to use Luke to get contextualized word representations (like BERT) and apply them for distributed representations of input to be integrated into my word-level sequence labeling model. However, the performance of my model dropped significantly (on the CoNLL2003 test dataset, the f1 score dropped from 90%+ to 20%+). My method of extracting contextualized word representations from LUKE is here:
I download the “luke_large_500k.tar.gz" pre-trained model and use the code for NER to get word representations for input.
Specifically, I gather the “word_hidden_states” tensor with self-constructed index to obtain the representation of each word in the sentence.
I have checked the entire process and found no errors. What I am confused about is why the use of the extracted word representation from LUKE will degrade the performance of the model so much. Is it inappropriate to use LUKE to obtain contextualized word representations and apply them to other sequence labeling models?
Thank you very much!

**Comment by ikuyamada** [comment]
Hi, thank you for raising issue! I think the word representations of LUKE should be used in a similar manner with BERT. I haven't tested the conventional NER models (with or without CRF), but because our span-based NER model only with word representations yields 92.9 performance (Table 6 in the paper), I think the conventional sequence-based model should achieves the similar score.

**Comment by steambread666** [comment]
Thanks for your reply!
